### PR TITLE
PR Module 17

### PR DESCRIPTION
**Pull request by jplealj**
image

### CODE REVIEW

**Review by holgiosalos — COMMENTED** [review]
Could you upload a screenshot of the browser not showing the pop-up? the step is the one when the test is adding the t-shirt to the cart

**Comment by jplealj** [comment]
image
is this step?

**Comment by holgiosalos** [comment]
> image
> is this step?

No, the previous step to that one

**Comment by jplealj** [comment]
image
this one is the previous

**Review by holgiosalos — APPROVED** [review]

**Pull request merged**
